# Generated by Django 2.0.2 on 2018-06-11 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default='write there', on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
