# Generated by Django 2.0.6 on 2018-07-04 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180704_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Another',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field_empty', models.CharField(default='boo', max_length=500)),
                ('integer_empty', models.IntegerField(default=0)),
                ('foreign_empty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='anothermodel',
            name='foreign_empty',
        ),
        migrations.DeleteModel(
            name='AnotherModel',
        ),
    ]
