# Generated by Django 2.0.6 on 2018-07-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180704_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='another',
            name='char_field_empty',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200),
        ),
    ]
